#ifndef CODEBLOCKS_TARGET_RELATION_TYPE_H
#define CODEBLOCKS_TARGET_RELATION_TYPE_H

#include "utilityEnum.h"

namespace Codeblocks
{

enum TargetRelationType
{
	CODEBLOCKS_TARGET_RELATION_IGNORE_TARGET,
	CODEBLOCKS_TARGET_RELATION_IGNORE_PROJECT,
	CODEBLOCKS_TARGET_RELATION_TARGET_BEFORE_PROJECT,
	CODEBLOCKS_TARGET_RELATION_TARGET_AFTER_PROJECT,
	CODEBLOCKS_TARGET_RELATION_UNKNOWN
};


}	 // namespace Codeblocks

template <>
Codeblocks::TargetRelationType intToEnum(int value);

#endif	  // CODEBLOCKS_TARGET_RELATION_TYPE_H
