# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Sourcetrail on Windows platform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - run: echo "Success"
